# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.TextField(),
        ),
    ]
