# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20171025_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.CharField(max_length=999),
        ),
    ]
