# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20171025_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='userkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quote', to='quotes.User'),
        ),
    ]
