# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20171026_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='favorite',
            field=models.ManyToManyField(null=True, related_name='user_favorite', to='quotes.User'),
        ),
    ]
